baseURL = 'spyingonscience.com'
title = 'spying on science'

languageCode = "en"
theme = "lightbi"
summaryLength  = "30"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
ignoreLogs = ['warning-goldmark-raw-html']


[Params]
selfHosted = true
mainSections = ["posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
hideAuthor = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
gcse = false
Lastmod = false
rss = true 
pagination = "10"
description="Unsere Welt hat so viele Wunder zu bieten. Spionieren wir sie gemeinsam bis ins kleinste Detail aus! #spyingonscience. Mein Name ist Andrea, ich bin passionierte Biologin & begeisterte Wissensvermittlerin."
lunrSearch = true
previewCardImagePlacement = "middle"
hidePostImage = false
tagSubtitle = "Here, you’ll discover the latest notes that explore new insights, and unique perspectives on the world."
homepageLayout = "profile" #blog
profileShortbio = "Unsere Welt hat so viele Wunder zu bieten. Spionieren wir sie gemeinsam bis ins kleinste Detail aus! #spyingonscience. Mein Name ist Andrea, ich bin passionierte Biologin & begeisterte Wissensvermittlerin."
profilePhoto = "logo.png"
favicon = true 

[pagination]
pagerSize = 9



[Params.Author]
  name = "Andrea Koplitz-Weißgerber"
  website = "https://www.spyingonscience.com/"
  authorInfo = "Unsere Welt hat so viele Wunder zu bieten. Spionieren wir sie gemeinsam bis ins kleinste Detail aus! #spyingonscience."
  authorPostImage = "/images/me.png"
  instagram = "spyingonscience"
  linkedin = "andrea-koplitz-weissgerber"





[[menu.main]]
    name = "  Aktuelles & Termine  "
    url = "/events/"
    weight = 2

[[menu.main]]
    name = "  Referentin  "
    url = "/wisskomm/"
    weight = 4


[[menu.main]]
    name = "  Limnologin  "
    url = "/limnologie/"
    weight = 3


[[menu.main]]
    name = "  Über  "
    url = "/ueber/"
    weight = 5

[[menu.main]]
    name = "  Impressum/Datenschutz  "
    url = "/contact/"
    weight = 6

#[[menu.main]]
#    name = "Blog"
#    url = "/posts/"
#    weight = 7


#[[menu.main]]
#    name = "Datenschutz"
#    url = "/privacy/"
#    weight = 8